version: '3.1'

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: fruity
      POSTGRES_USER: candidate
      POSTGRES_PASSWORD: candidate
    volumes:
      - ./init_fix.sql:/docker-entrypoint-initdb.d/init_fix.sql
    ports:
      - "5432:5432"
